##chars.py

#tabs
angle_left_bold           = '┏'
angle_left_reversed_bold  = '┗'
angle_right_bold          = '┓'
angle_right_reversed_bold = '┛'
line_horizontal           = '─'
line_horizontal_bold      = '━'
line_vertical             = '│'
line_vertical_bold        = '┃'
T                         = '┬'
T_bold                    = '┯'
T_reversed                = '┴'
T_reversed_bold           = '┷'
T_left_halfbold0          = '┠'
T_left_doubled2           = '╠'
T_right_halfbold0         = '┨'
T_right_doubled2          = '╣'
cross                     = '┼'
cross_doubled             = '╬'
slash_left                = '╱'
slash_right               = '╲'
space_full                = '　'
space_half                = ' '
empty                     = ''
line_break                = '\n'
#Chinese_pieces
pawn_alpha      = '兵'
pawn_beta       = '卒'
cannon_alpha    = '炮'
cannon_beta     = '砲'
chariot_alpha   = '车'
chariot_beta    = '車'
steed_alpha     = '马'
steed_beta      = '馬'
vizier_alpha    = '相'
vizier_beta     = '象'
chevalier_alpha = '士'
chevalier_beta  = '仕'
enemy           = '敌'
#Chinese_sentences
river_left  = '楚河'
river_right = '汉界'
admirals    = '将帅'
XiangYu     = '项羽'
LiuBang     = '刘邦'
round_belongs = '的回合'
win   = '胜利！！！'
cannot_select = '无法选中！'
selected = '已选中：'
saved = '残局已保存！'
helping = '点击窗口左下角控制视角左右移动，右下角控制视角俯仰，左上角保存残局。'
